#define degToRad(angleindegrees) ((angleindegrees) * 3.1415926535 / 180.0)
#include "drawUtils/drawPill.cpp"
#include "drawUtils/drawEllipse.cpp"
#include "drawUtils/drawHalo.cpp"
#include "drawUtils/drawArch.cpp"
#include "drawUtils/hsv2rgb.cpp"
#include "drawUtils/rgb2hsv.cpp"

// Character Utilities
#include "charUtils/draw_a.cpp"
#include "charUtils/draw_b.cpp"
#include "charUtils/draw_c.cpp"
#include "charUtils/draw_d.cpp"
#include "charUtils/draw_e.cpp"
#include "charUtils/draw_f.cpp"
//#include "charUtils/draw_g.cpp"
//#include "charUtils/draw_h.cpp"
//#include "charUtils/draw_i.cpp"
//#include "charUtils/draw_j.cpp"
//#include "charUtils/draw_k.cpp"
//#include "charUtils/draw_l.cpp"
//#include "charUtils/draw_m.cpp"
//#include "charUtils/draw_n.cpp"
//#include "charUtils/draw_o.cpp"
//#include "charUtils/draw_p.cpp"
//#include "charUtils/draw_q.cpp"
//#include "charUtils/draw_r.cpp"
//#include "charUtils/draw_s.cpp"
//#include "charUtils/draw_t.cpp"
//#include "charUtils/draw_u.cpp"
//#include "charUtils/draw_v.cpp"
#include "charUtils/draw_w.cpp"
#include "charUtils/draw_x.cpp"
#include "charUtils/draw_y.cpp"
#include "charUtils/draw_z.cpp"
// :v
